# Generated by Django 4.1.7 on 2023-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_driver_id_alter_driver_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
