# Generated by Django 4.1.7 on 2023-05-20 02:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profilepic_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(upload_to=accounts.models.profile_pic_upload_path),
        ),
    ]
