# Generated by Django 4.2.1 on 2023-10-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_birthdate_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, default='static/picture/user.png', null=True, upload_to='profile_pics/'),
        ),
    ]
